### ISSUE TITLE
DXF file is scaled incorrectly

### ISSUE THREAD

**Issue by Ash2772** [ElvinC/openchute#1]
I've made several chutes using openchute, very easy to use. For each I exported the DXF file for laser cutting. The imported file always appeared very small, I would have to make it 110 or 1100 times bigger or something like that in order for it to be the correct size. The dimensions plot on openchute made this a bit easier. I was using the lightburn software for the laser cutting.

**Comment by ElvinC** [comment]
From what I've read, DXF files are unitless by default, so I used mm. You can check in the lightburn settings to make sure it uses mm
![image](https://github.com/ElvinC/openchute/assets/20195216/0e94b85e-fb6a-405e-af7f-aef412d2ffde)

**Comment by Ash2772** [comment]
Thanks I've gotten it to work now, though I had to select meters instead of mm.

**Comment by ElvinC** [comment]
which version are you using? In some earlier builds I used m, but in the exe downloaded from git, it should be mm

**Comment by Ash2772** [comment]
Oh, yes I was using an older version it is good now, thanks.
